spring:
  datasource:
    druid:
      username: root
      password: 110455
      url: jdbc:mysql://8.130.98.101:3306/my-chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      max-active: 8
      query-timeout: 10000

  # redis 配置
  redis:
    port: 6379
    host: 8.130.98.101
    password: 110455
server:
  port: 8083
  servlet:
    context-path: /chat
mybatisplus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
